### ISSUE TITLE
Support under-specified Python versions

### ISSUE THREAD

**Issue by milliams** [abatilo/actions-poetry#12]
I tried to use your action with a matrix-specifed Python version. I set it like:

```yaml
...
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version:  ${{ matrix.python-version }}
        args: install
...
```

and I expected that `[3.6, 3.7, 3.8]` would choose the latest release of each version (so 3.6.9, 3.7.5 and 3.8.0).

Instead I get an error:

```
python-build: definition not found: 3.6

The following versions contain `3.6' in the name:
  3.3.6
  3.6.0
  3.6-dev
  3.6.1
  3.6.2
  3.6.3
  3.6.4
  3.6.5
  3.6.6
  3.6.7
  3.6.8
  3.6.9
  activepython-3.6.0
  pypy3.6-7.0.0-src
  pypy3.6-7.0.0
  pypy3.6-7.1.0-src
  pypy3.6-7.1.0
  pypy3.6-7.1.1-src
  pypy3.6-7.1.1
  pypy3.6-7.2.0-src
  pypy3.6-7.2.0

See all available versions with `pyenv install --list'.

If the version you need is missing, try upgrading pyenv.
pyenv: version `3.6' not installed
```

Perhaps https://github.com/momo-lab/xxenv-latest could be used? Otherwise, is it possible to use the logic from https://github.com/actions/setup-python to do this?
