### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by mr-bjerre** [abatilo/actions-poetry#26]
Good job on a very simple api for this action.

Is it possible to add some caching though? In your example python is being installed twice even. It would be nice if the environment would be cached between pushes so only the testing would be run on pushes (unless there is a dependency or similar change of course)

```yaml
name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        working_directory: ./working_dir # Optional, defaults to '.'
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        working_directory: ./working_dir
        args: run python -m pytest --cov=src --cov-branch --cov-fail-under=100 tests/
```
