### ISSUE TITLE
V2 only usable via branchname specification instead of versioned action

### ISSUE THREAD

**Issue by mcbobke** [abatilo/actions-poetry#38]
Example workflow from my project:

```
name: Poetry build and test
on: push
jobs:
  execute:
    name: Execute
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
      fail-fast: true
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.3
      - name: Install required version of Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Poetry
        uses: abatilo/actions-poetry@master                  <--------------------------------------
        with:
          poetry-version: 1.1.2
      - name: Set up Poetry virtual environment
        run: poetry env use python${{ matrix.python-version }}
      - name: Install project dependencies
        run: poetry install
      - name: Run tests with Poetry
        run: poetry run pytest
```

The [marketplace](https://github.com/marketplace/actions/python-poetry-action) only has V1 available.
