### ISSUE TITLE
please document how the cache should be configured using this action

### ISSUE THREAD

**Issue by lucsorel** [abatilo/actions-poetry#64]
thank you @abatilo for this github action :pray: 

Before using your action, I:
- installed poetry
- then installed python defining a cache

```yaml
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry' # <- this is where a cache was defined for poetry
      - name: Install dependencies
        run: poetry install
```

I tried using the actions-poetry action like this:

```yaml
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry' # <- this cause the installation to fail
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1
      - name: Install project dependencies
        run: poetry install
```

The `cache 'poetry'` line in the actions/setup-python@v4 action causes the job to fail:

>  Error: Unable to locate executable file: poetry. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

Can you please tell me (and add in the README file) how one should set up a cache for poetry to speed up the download of dependencies? :pray:

**Comment by kosinal** [comment]
I used caching in my project with following setting:

In definition of the github action job:
``` yaml
- uses: actions/cache@v3
  name: Cache .venv
  with:
    path: ./.venv
    key: venv-${{ hashFiles('poetry.lock') }}
```

Add poetry.toml file in root of project with following settings:
``` toml
[virtualenvs]
create = true
in-project = true
```

How does it work:

- With settings in poetry.toml, virtual environment is being created inside project in .venv folder
- I do cache .venv folder based on hash of my poetry.lock file, which contains current dependencies
- When my CI job stars, I can see following:
```
Run actions/cache@v3
  with:
    path: ./.venv
    key: venv-1cdf[2]
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
 
Received 855004 (100.0%), 144.3 MBs/sec
Cache Size: ~82 MB (85500470 B)
/usr/bin/tar -xf /home/runner/work/_temp/8cca7c6a-f27b-448d-8c10-5f718fafd2ed/cache.tzst -P -C 
Cache restored successfully
Cache restored from key: venv-1cdf2[9]

# poetry install
Installing dependencies from lock file

No dependencies to install or update
```

Using this, when dependencies do not change in build, I do not have to download and install it again, but I can skip this step and do testing.

**Comment by lucsorel** [comment]
:pray: thank you very much for your comprehensive explanation :smiley: 

Just to make sure I got it right, can you confirm that the steps would be in the following order, please?

```yaml
name: Python package
# ...
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1
      - uses: actions/cache@v3
        name: Cache .venv
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install project dependencies
        run: poetry install
      - name: Run automated tests
        run: poetry run pytest -v 
```

Is that ok?
