### ISSUE TITLE
Python version not respected on macOS

### ISSUE THREAD

**Issue by alexdewar** [abatilo/actions-poetry#72]
I'm currently using v2.3.0 on my repo without issue. We run tests on Windows, Linux and macOS using Python 3.11.

However, if I upgrade to v3.0.0, the macOS runner seems to try to use Python 3.12, even though I'm using https://github.com/actions/setup-python/tree/v5/ to set the version to 3.11. Any ideas?

**Comment by hxii** [comment]
Seems like this is caused by the jump from using `pip` to using `pipx` in order to install `poetry`.
Perhaps an interim solution could be to replace
https://github.com/abatilo/actions-poetry/blob/d79ef3c982151168214cfbd228e0b76cf7f14cae/action.yml#L25
with
```
pipx install poetry --python $(python --version)
```

**Comment by j-adamczyk** [comment]
Bump, since this is very problematic, and fix is incredibly simple. Note that just `$(python --version)` will not work, since pipx requires specific format, e.g. `pipx install poetry --python python3.9` (note `python3.9` format). Furthermore, assuming that default Python should be used is not ideal.

As a quickfix, we replaced this action with (we use Python versions matrix for testing):
```
pipx install poetry --python python${{ matrix.python-version }}
```

The most flexible solution probably is having an optional argument with Python version to select.

**Comment by silentworks** [comment]
Another workaround to this issue is to put the `actions/setup-python` step after the `abatilo/actions-poetry` step, this way `poetry install` will use the `python version` that was installed after rather than the global python.

```yml
- name: Set up Poetry
  uses: abatilo/actions-poetry@v4
  with:
    poetry-version: latest

- name: Set up Python ${{ matrix.python-version }}
  uses: actions/setup-python@v5
  with:
    python-version: ${{ matrix.python-version }}
    cache: 'poetry'
```
